### ISSUE TITLE
Why there is difference between CHARMM36 simulation results from POPS:POPC mixture and pure POPS?

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NMRlipidsIVotherHGs#1]
There is significant difference between CHARMM36 simulation results from POPS:POPC mixture and pure POPS in Fig. https://github.com/NMRLipids/NMRlipidsIVotherHGs/blob/master/Figs/HGorderparametersPOPS-eps-converted-to.pdf

Importantly, the pure POPS simulations are closer to experiments from POPC:POPS mixture than simulations with molecular fractions corresponding experimental setup.

Potential reasons I have in mind:
1) The simulations with POPC are too short (pure POPS are quite long).
2) There is difference in initial structure and/or parameters. POPS:POPC mixtures are directly from CHARMM GUI. Where are the pure POPS simulation files taken from?
3) The presence of POPC has significant influence on POPS structure.  
4) There are also different counterions used; potassium in POPS:POPC mixture and sodium in pure POPS. I used potassium to avoid overbinding discussed in NMRlipids II.

**Comment by TomPiggot** [comment]
Hi,

The structures and parameters are also from the CHARMM-GUI (with the newer NBFIX for the sodium interactions).

I will setup some simulations with i) pure POPS and potassium, (ii) POPC:POPS with sodium and (iii) POPC:POPS with potassium. This should allow diagnosis of what is going on, I could easily imagine any of 1, 3 and 4 being true.

Cheers

Tom

**Comment by TomPiggot** [comment]
This set of simulations have now finished. I've done the same analysis as before (final 100 ns of 500 ns simulations; two simulations for each setting with different starting velocities). I also ran sims for both the 8A and 10A switching points for the vdW interactions but I'm just showing the 10A ones below (they give effectively the same results). The results below have the same order of results as before:

POPS + K

v1

1 -0.0641443 
2 0.0594299 -0.0557454
3 -0.224778 -0.232332
4 -0.210426 
5 -0.212462 -0.0544763

v2

1 -0.0683185 
2 0.0661756 -0.0369859
3 -0.204837 -0.240731
4 -0.201182 
5 -0.194749 -0.0458282

So, very similar results to my original POPS + Na simulations (with some slight differences for one of the hydrogens attached to the alpha carbon perhaps)

POPS/POPC + K

v1

1 -0.132095 
2 0.0868788 -0.0966833
3 -0.256231 -0.248281
4 -0.223562 
5 -0.203674 -0.0449641

v2

1 -0.14763
2 0.116538 -0.10411
3 -0.236263 -0.250079
4 -0.205888 
5 -0.183628 -0.0452724

So these are much closer to the originally reported POPS/POPC with potassium results. 

POPS/POPC + Na

v1

1 -0.132365 
2 0.0714638 -0.104298
3 -0.244233 -0.244513
4 -0.221189 
5 -0.200132 -0.022929

v2

1 -0.132797 
2 0.0495719 -0.10143
3 -0.234478 -0.252475
4 -0.232956 
5 -0.224599 -0.0155944

Very similar results to the POPS/POPC and potassium mixture.

I think this nicely shows that the majority of the differences in order parameters for the beta and alpha carbons are almost certainly arising due to the mixture of POPS with POPC (I guess there are other differences in these simulations, like the overall number of ions in the system that could potentially be playing a role too albeit I think this is far less likely). I've not looked yet at the POPC order parameters to see if these are altered by the presence of POPS.

If you want the results for the ones with the 8A switching point let me know.

Cheers

Tom

**Comment by ohsOllila** [comment]
There are now also experimental data from both pure POPS and POPC:POPS 5:1 mixture. There seems to be some differences also there, but not similar as in simulations. 
![hgorderparameterspops](https://user-images.githubusercontent.com/7114769/29615821-fa5bb3b8-8817-11e7-8b49-122b66a1172f.png)

**Comment by ohsOllila** [comment]
@TomPiggot could you confirm the mole fraction of PS in PC bilayers in the above simulations with different counterions?

**Comment by ohsOllila** [comment]
I added a new figure showing the effect of the addition of PC to the PS headgroup order parameters in simulations and experiments (assuming that the data by @TomPiggot above had 83% of POPC): 

![hgorderparameterspspgvspc](https://user-images.githubusercontent.com/7114769/32110249-be5358c0-bb3f-11e7-9833-0742ec6421e2.jpg)

It seems to me that the CHARMM36 model do not get this quite right.

**Comment by TomPiggot** [comment]
The ratio is 5:1 PC to PS as per the experimental data, so your assumption of 83% PC is correct. The numbers of lipids per leaflet are 11 PS and 55 PC.

On a completely different note, if possible can you change the colours you used in these plots? Being colour blind I find it difficult to distinguish the red and black easily when they are presented like this (i.e. when the lines are close together and/or overlap). Almost any other colour with black (blue, pink, orange, yellow, green, etc) is easier for me. Thanks!

**Comment by TomPiggot** [comment]
And I should have said I agree, it seems that the force field doesn't quite do this right. Do you know what the amount of error associated with the experimental data is (sorry if I missed already this on some of the other posts)?

**Comment by TomPiggot** [comment]
@ohsOllila Did we want simulations of this PC/PS mixture with other force fields to look at this too? Or are there other simulations that would be better to run for this project?

**Comment by ohsOllila** [comment]
Thanks for the feedback about colours. We are trying to take this into account for the final figures and this is very useful. The color issue is complicated since we should keep the consistent labeling throughout the manuscript, and preferably throughout the NMRlipids project (which is not yet the case in this work). So this requires some improvement anyway and we need to come back to this. 

The accuracy of order parameters is discussed in sections 2.4. and 2.5. in NMRlipids V publication (http://dx.doi.org/10.1016/j.bbamem.2016.01.019) and in the older blog post http://nmrlipids.blogspot.fi/2014/02/accuracy-of-order-parameter-measurements.html. Shortly, the order parameter values are known with the accuracy of roughly 0.02, but the measurements of the changes are much more accurate.

There are some Berger (http://nmrlipids.blogspot.com/2017/03/nmrlipids-iv-headgroup-glycerol.html?showComment=1504821167969#c9105443281626699475) and MagRog (http://nmrlipids.blogspot.com/2017/03/nmrlipids-iv-headgroup-glycerol.html?showComment=1505891206126#c454161654494186251) simulations reported in the blog, which are not yet analyzed. POPC/POPS mixtures simulated with Slipids might be somewhat interesting, although the PS structures in Slipids do not look very promising.

**Comment by TomPiggot** [comment]
Ah yes, I remember reading the blog post on the errors now, thanks for link.  And I completely understand about wanting to keep the colours consistent too. Thicker lines definitely help too but can be difficult to use if you have lots of lines in one figure.

Slipids mixtures would be easy to setup (the structures would be identical to the CHARMM36 ones) but if it's not going to be all that useful I won't bother for the time being.

**Comment by ohsOllila** [comment]
@TomPiggot could you share also the trajectories and data for simulations with K as a counterion in Zenodo (or point the links, if they are already there)?

**Comment by TomPiggot** [comment]
Sorry for the delay, finally getting around to this. I'll make the uploads and post the links

**Comment by TomPiggot** [comment]
@ohsOllila here you are:

POPS with K: https://zenodo.org/record/1182654
POPS/POPC with K: https://zenodo.org/record/1182658
POPS/POPC with NA: https://zenodo.org/record/1182665

**Comment by ohsOllila** [comment]
This issue is pretty much solved. The results reported here are in figure:
https://github.com/NMRLipids/NMRlipidsIVotherHGs/blob/master/Figs/HGorderparametersPCvsPS-eps-converted-to.pdf
and the topic is discussed in the manuscript.

I will close this.
