### ISSUE TITLE
CHARMM36 simulations with new NBfix

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NMRlipidsIVotherHGs#100]
I think that for the revised version we should run the CHARMM36 simulations using also the new NBfix parameters for Calcium (http://dx.doi.org/10.1021/acs.jpcb.7b10730). The easiest way would be probably to change the parameters in these systems to the new NBfix and rerun:
https://doi.org/10.5281/zenodo.2542151
https://doi.org/10.5281/zenodo.2542176
https://doi.org/10.5281/zenodo.2542135

However, I am not sure what CHARMM-GUI is nowdays printing out. Maybe the new NBfix parameters are already included there? In this case, it might be easier just to create new systems with CHARMM-GUI.

**Comment by nencini** [comment]
CHARMM-GUI parameters have been changed since the time simulations mentioned above were run. Compare to the parameters from the paper, http://dx.doi.org/10.1021/acs.jpcb.7b10730, there is one extra line for POPS-oxygen Ca interaction

CHARMM-GUI parameters:
[ nonbond_params ]
; i	j	func	sigma	epsilon
    CAL     CLA       3.32037952251e-01  5.61342176000e-01 
    CAL     O2L       2.90076622626e-01  5.02080000000e-01 
    CAL     OCL       2.87314836600e-01  5.02080000000e-01 

Han parameters:
CAL    CLA         3.32037952251e-01  5.61342176000e-01
CAL    OG2P1    2.90076622626e-01  5.02080000000e-01

I am running the simulations mentioned above with parameters from the paper.

**Comment by ohsOllila** [comment]
The results are now in the manuscript, I will close this.
