### ISSUE TITLE
Table II

### ISSUE THREAD

**Issue by markussmiettinen** [NMRLipids/NMRlipidsIVotherHGs#43]
+ remove the explicit POPS:POPC, as this is the same for all rows, and put e.g. in the column title
+ explicitly state the number of independent repeats, e.g., by having 2 x 500 in the t_sim
+ the N_l -column only repeat the mole fraction -> give total number of lipids instead?
+ footnotes h) and i) are identical -> merge

**Comment by hsantila** [comment]
There is also something wrong with the POPC:POPC (5:1)/K+ records, the reference points to Ca2+ simulations

I'll made a pull request noting this and applying all of Markus' suggestions except the first one, because I think having the POPS:POPC in the row nicely summarizes the simulation and gives explicit definition how the following ratio is calculated

**Comment by ohsOllila** [comment]
I agree with @hsantila about not removing POPS:POPC. 

The same reference to POPC:POPC (5:1)/K+ files with MacRog contains also a simulation without calcium. However, it is written in Zenodo that "All simulations were 600 ns long, and the last 300 ns are included in the uploaded trajetories.", which does not seem to the case for the simulation without calcium. The simulation lengths in the table are correct, but I think that the description in the Zenodo does not apply to the simulation without calcium.

I will close this issue because the original suggestions are included in the manuscript (except the first), and the unclarity in Zenodo is not directly related to NMRlipids IV manuscript.

**Comment by ohsOllila** [comment]
Also the information about simulation lengths in Zenodo record is now corrected.
