### ISSUE TITLE
Figs 6 and 10 (ion distributions)

### ISSUE THREAD

**Issue by markussmiettinen** [NMRLipids/NMRlipidsIVotherHGs#44]
+ format like NMRlipids II Figs 4 and 6

**Comment by ohsOllila** [comment]
I could not find the source files for Figs 4 and 6 from the NMRlipids II git. Are they missing or are they in some non-standard location (standard would be Fig/scripts/ folder https://github.com/NMRLipids/lipid_ionINTERACTION/tree/master/Fig/scripts)?

**Comment by jsmaatta** [comment]
There is now an update for figs 6 and 10 based on NMRlipids II. The scripts to generate the new figs are now in https://github.com/NMRLipids/NMRlipidsIVotherHGs/tree/master/Figs/scripts

The color scheme is based on the old NMRlipids II Figs. 4 and 6 but could be easily changed for better clarity.

**Comment by markussmiettinen** [comment]
> I could not find the source files for Figs 4 and 6 from the NMRlipids II git. Are they missing or are they in some non-standard location (standard would be Fig/scripts/ folder https://github.com/NMRLipids/lipid_ionINTERACTION/tree/master/Fig/scripts)?

They are, non-standardly, in 
https://github.com/NMRLipids/lipid_ionINTERACTION/tree/master/scripts/analysisForFigures_3_4_6_and_S2_S3_S5_S7_S8
Script names: **plot_Na_densities.gpl** and **plot_Ca_densities.gpl**.

**Comment by jsmaatta** [comment]
Hi,

There's now an update on Fig. 6 with phosphate peaks for 5 first force fields.

Thanks for pointing out  the script location! The phosphate peaks are calculated with the scripts from Markus: centerTheBilayer.sh and calculatePeakPositions.sh (peak position for phosphate: M_G3P2_M). The scripts are found in the folder in the above post.

I hope I did not make any mistakes running the scripts. Luckily, the phosphate peaks seem to make sense for volume conservation: smaller area corresponds to a thicker bilayer.

Interestingly, the phosphate peak difference between NA and K is big for MACROG but then again so is the difference in the area per lipid.

A note on colors: since black is generally reserved to experimental data, the ion densities are plotted now in green. I also made an another version with colors matching those of Figure 3: NAdensPOPSformattedColorVariation.pdf

I did not find any POPS mapping files for Lipid17 or Gromos in the MATCH/MAPPING folder. Maybe they're somewhere else?

**Comment by markussmiettinen** [comment]
Nice!

I would show just full integers (2.0 -> 2) on the y-axis, plus half points with a minor tic.

Y-axis label could read 'number density of _counter_ ions'.

MACROG -> MacRog and CHARMM36ua -> CHARMM36-UA to keep with the style used in previous publications.

**Colors** I like more the one where the color is not matched to the force field, as it looks more calm.

**Mapping files** for Lipid17 and GROMOS-XXXs haven't probably been done, as this is the first time we have these force fields.

Question: There are typically 2 simulations for each system. Are the two lines from these two simulations? Or are they the two leaflets (this is how I think I had it before)?

**Comment by ohsOllila** [comment]
I am not aware of the existing mapping files for Lipid17 or GROMOS-XXX. 

For Lipid17, I have used the order parameter definition file here: https://github.com/NMRLipids/MATCH/blob/master/Data/Lipid_Bilayers/DOPS/T303K/MODEL_LIPID17/order_parameter_definitions_Lipid14_DOPS.def

Nevertheless, the mapping file for lipid14 POPC might be very similar for lipid17 POPS. I have now copied this from NMRlipid II repository to here: https://github.com/NMRLipids/MATCH/blob/master/MAPPING/mappingPOPClipid14.txt

**Comment by ohsOllila** [comment]
I agree with Markus about the colors.

**Comment by jsmaatta** [comment]
Hi,

Thanks for the comments and the mapping files. Really helpful!

I updated the figures according to the comments. The CaCl plot also now has Cl densities (todo point 10). There's also a Red version of the CaCl plot just in case. The CaCl plot lacks the phosphate/counterion densities for ff99 because that data seems to be from AMBER simulations only.

For the phosphate peaks one only needs the naming g3 atom, last carbon of SN-1 tail and the P atom. So yes, the POPC mappings often were useful. Lipid17 naming differs a bit from lipid14 so I hacked a version from lipid14 mappings just to get the phosphate peaks. Same for GROMOS. 

For the question about the two lines:
The two lines are the two different leaflets just like in previous NMRlipids. The density data is straight from Samuli's previous version of the figures (plotNAdensPOPS.gpl) which has the data for two leaflets and I think is an average over all simulations. The plot just mirrors it over bilayer center just like before.

**Comment by markussmiettinen** [comment]
Very nice!

**Fig 6.**

I think the **A_pl values** give the impression that the area was held fixed at these values, which it was not, but the areas were measured from the simulations. I would thus 1) move them to the right hand side of the panels, and also 2) it would be good if we added error estimates, as this would indicate that these are measured values.

Also, I would move the other information that was actually fixed to the left hand side of the figure. That is, the **counterion type** and the **ion force field**. I would also align these texts to left, and align them (to left) with the FF name (CHARMM36) in the topmost panel.

**Comment by markussmiettinen** [comment]
**Fig. 10**

- LIPID17 -> Lipid17
- I like more the 'green version'
- I would use the same line color for the anions as cations, but take a thin and dotted line type as was done in NMRlipids II
- probably we can leave the mentioning of ion types (Ca2+, Cl-) out from the plots, and mention them in the caption & show them visually with a cartoon like we did in NMRlipids II. Then we can also move the "Dang Ca2+"  and "ff99 Ca2+" on the left hand side, after the concentrations.
- align concentrations to the left according to FF name in the topmost panel

**Comment by markussmiettinen** [comment]
> For the question about the two lines:
> The two lines are the two different leaflets just like in previous NMRlipids. The density data is straight from Samuli's previous version of the figures (plotNAdensPOPS.gpl) which has the data for two leaflets and I think is an average over all simulations. The plot just mirrors it over bilayer center just like before.

I don't think it is an average over all simulations. To me it looks like Samuli's script is only using the _v1_ of the two trajectories. The _v2_ is not used at all.

**Comment by ohsOllila** [comment]
In Fig. 6, please update 
Gromos-CKPM -> GROMOS-CKPM
Gromos-CKP -> GROMOS-CKP

**Comment by ohsOllila** [comment]
> In Fig. 6, please update
> Gromos-CKPM -> GROMOS-CKPM
> Gromos-CKP -> GROMOS-CKP

I was able to do this easily myself so it is done now.

**Comment by ohsOllila** [comment]
I have now updated also the figure captions in commit: https://github.com/NMRLipids/NMRlipidsIVotherHGs/commit/54891740d8a6ed5717502efbc8f616dd9e44ec6f

Are we done with these figures? Can I close this issue?

**Comment by markussmiettinen** [comment]
I am happy with the current appearance of Figs 6 and 10. On my behalf you can close this one.

**Comment by markussmiettinen** [comment]
To me it seems that the two ion models for Lipid17 have been switched in the key. Is this so, @jsmaatta? If it is, could you correct it, please?

**Comment by markussmiettinen** [comment]
Also, it seems that the Cl ion density profile for the (now shown in yellow) system was also made available by @batukav on https://github.com/NMRLipids/MATCH/tree/master/Data/Lipid_Bilayers/POPS%2B83%25popc%2B500mMCaCl/T298K/MODEL_LIPID17.

Or, @batukav, is the third column not the chloride density profile? If it is, we could add that too in the plot, @jsmaatta.

**Comment by jsmaatta** [comment]
My pdfcairo is currently not working so the text in gnuplot figures is not correctly formatted. But I plotted the Cl ion profile here (yellow dashed line) and it seems very odd. I dont think this is a Cl density, probably phosphate density instead?

![CaDens](https://user-images.githubusercontent.com/11630230/64601345-7404cb00-d3c5-11e9-8f6c-1691c69d622a.png)

**Comment by markussmiettinen** [comment]
Thanks! That indeed does not seem to be Cl. Maybe it is some sort of error estimate? Namely, it seems to be nonzero for just the bins for which the second column also is nonzero.

Concerning the key. @jsmaatta, do you agree with me that the current green line is actually with Dang and the current yellow with ff99? If so, I can also easily change the figure.

**Comment by jsmaatta** [comment]
Yes I agree. Good eyes!

Figure 6 is correct but 10 was indeed wrong. The gnuplot file is now changed.

Could you or someone with working pdfcairo run the "gnuplot plotCAdensPCPSmixtureLOWconsformatted.gpl" command to get the pdf file itself?

**Comment by ohsOllila** [comment]
I ran the command and added the result in git, looks good now.

**Comment by jsmaatta** [comment]
Great! Thank you.
