### ISSUE TITLE
Table of content figure

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NMRlipidsIVotherHGs#89]
We need the table of content figure for the manuscript about PS lipids. I guess that something utilizing the overlayed snapshots, e.g., in Fig. 4 might work.

The ACS guidelines are here: 
https://pubs.acs.org/paragonplus/submission/toc_abstract_graphics_guidelines.pdf

**Comment by jmelcr** [comment]
TOC graphic idea: overlayed structures without cations on one side and a "question mark" instead of a structure with a cation in its vicinity on the other side would fit well to the title and to one of the main outcomes of the paper. 

What do you think?

**Comment by ohsOllila** [comment]
This sounds like a good start. Maybe you could make a rough draft about this?

I think that it would be important to emphasize in the figure that we focus on PS lipids. 

Also, one option is to somehow utilize the structures in figures 4, S9 and S12.

**Comment by jmelcr** [comment]
Here is a sketch of a candidate TOC graphic:
[TOC_graphic.pdf](https://github.com/NMRLipids/NMRlipidsIVotherHGs/files/3501979/TOC_graphic.pdf)

**Comment by ohsOllila** [comment]
I think that it would be good to have also a bilayer in the figure. Then maybe somehow indicate that the shown structures are observed in a bilayer. Maybe NaCl and CaCl2 could be replaced with a schematic presentation of Na+ and Ca2+ ions.

**Comment by jmelcr** [comment]
I tried to implement the above mentioned comments:
[TOC_graphic.pdf](https://github.com/NMRLipids/NMRlipidsIVotherHGs/files/3510171/TOC_graphic.pdf)

**Comment by ohsOllila** [comment]
Thanks, maybe the text and question mark could take less space. Also, there is a typo in "structure". 

Are there any comments or suggestions from other people?

**Comment by jmelcr** [comment]
That is easy to change. I will only return to my office next week, so you can expect the updated TOC graphic on Tuesday latest. We may even get some further feedback by that time...

I already got feedback from a college that the left-to-right content is not balanced with good graphics to the left and just text to the right. This is rather "by design", but it may not be clear from the first glance. I think about the text to the right as a dominant of the TOC which brings the message in simple typeset font suppressing all the graphics to the left slightly into the background. 
Any suggestions to improve this are welcome. 

Also, if anyone would like to take over, I can share the source file for Scribus DTP.

**Comment by ohsOllila** [comment]
One option might be to rotate the bilayer 90 degrees and make it thicker.

Source file might be useful anyway, if someone wants to try something with it.

**Comment by jmelcr** [comment]
I was afraid that the horizontal membrane would not fit into the ACS format for TOC graphics, but I managed after few tweaks. Here is the figure, which includes as much from the above comments as possible:
[TOC_graphic_3.pdf](https://github.com/NMRLipids/NMRlipidsIVotherHGs/files/3540402/TOC_graphic_3.pdf)

Here the source files zipped together:
[nmrlipid4_TOCfig.tar.gz](https://github.com/NMRLipids/NMRlipidsIVotherHGs/files/3540414/nmrlipid4_TOCfig.tar.gz)
the "*.sla" file is the main file generated with [Scribus DTP](https://www.scribus.net/), which is directly available in most Linux repositories.

**Comment by mattijavanainen** [comment]
[TOC.pdf](https://github.com/NMRLipids/NMRlipidsIVotherHGs/files/3542564/TOC.pdf)
I put this together today. If there's support for it, I'm ready to hear suggestions and improve it further. I can also share the source files (It's made with Inkscape) if someone wants to work on it.

**Comment by markussmiettinen** [comment]
Nice work guys!

To me the most important message of the abstract appears to be: "We show large discrepancies between different force fields and that none of them reproduces NMR data within experimental accuracy." I think it would be good if the TOC figure would visualize this message.

To this end, I would drop the ions from the TOC, and focus only on the PS headgroup structure.

I would combine elements from both Matti (the nice visualization of the membrane) and Joe (the text highlighting the key question, plus the nice visualization of the headgroup structures observed). So something along these lines (note that this is just a quick mock up to visualize what I am after):
![IMG_0392](https://user-images.githubusercontent.com/5721866/63773223-0643a400-c8db-11e9-9cbe-6dc5811a1e41.JPG)
It would be good, of course, if Matti's bilayer would use the same colour code as the structure snapshots (to be taken from Fig S9) on the right. Also, I am not sure which force fields to show on the right, just took these more or less randomly...

**Comment by ohsOllila** [comment]
I like the idea of showing structures from different force fields, these are currently only in SI. For this, I would choose CHARMM36, Berger, MacRog, and Lipid17. They are all clearly different.

**Comment by mattijavanainen** [comment]
First, I don't see the point of the text in Markus's proposal — it essentially repeats the paper title, which appears anyway always next to the TOC. Secondly, a reader will likely have no clue what the structural ensembles depict without reading the paper. Thirdly, if these ensembles are to be included, their size has to be drastically increased for them to be readable. But if the text is removed, this could work.

@markussmiettinen: The Inkscape file (.svg) is included in the attached zip in case you want to use some elements from my draft.

[TOC.zip](https://github.com/NMRLipids/NMRlipidsIVotherHGs/files/3547637/TOC.zip)

**Comment by markussmiettinen** [comment]
@mattijavanainen: How difficult would it be for you to change the colouring scheme to match the scheme used in Fig S9? (Would be enough to recolour those three carbons in the highlighted lipid headgroup with that pretty green.)

**Comment by mattijavanainen** [comment]
@markussmiettinen: here's one with water surface and one without. Crop them to your liking:

![pops_green_water](https://user-images.githubusercontent.com/4508782/63871956-8ba38300-c9c5-11e9-99a2-e6f5917b316e.png)
![pops_green](https://user-images.githubusercontent.com/4508782/63871958-8ba38300-c9c5-11e9-9c7b-64be22592e5f.png)

**Comment by ffavelar** [comment]
I think Josef's proposal TOC_graphic_3.pdf is great but with Matti's bilayer representation.

**Comment by markussmiettinen** [comment]
![toc_small](https://user-images.githubusercontent.com/5721866/63953925-8d7f4c00-ca82-11e9-90ab-15d05d3b8e2e.jpg)

**Comment by ohsOllila** [comment]
I would maybe remove the "Does MD match NMR" text box, remove the green flag from MacRog completely and make flag stronger in CHARMM36.

**Comment by markussmiettinen** [comment]
I would keep the text box, or change it to something else that tells that we dealt with MD and NMR, as these are not mentioned in the title.

**Comment by jsmaatta** [comment]
Hi,

I like the latest figure from Markus that combines good ideas from Josef and Matti. (Matti's voltage meter figure is also pretty funny. I liked that idea too. Maybe use it for a paper that focuses on ions.)

I would also add that in addition to the Markus' message "We show large discrepancies ...",  there is also the message of "We gathered plenty of previous and produced new experimental NMR data for PS lipids." So that this paper could be the "one-stop paper for target data" if one wants to fix the errors in MD FFs!

So here is an attempt to highlight the NMR part in the TOC by adding simplified spectra from experiments. The downside is that this makes the figure feel a bit busy. Heres couple versions with very minor diffences and a photoshop .psd file with all the layers so its easy to edit.

But I'm fine with the previous figures too. Good work.

-Jukka

More space:
![toc1](https://user-images.githubusercontent.com/11630230/64030190-c127a800-cb4e-11e9-8251-ccf6a6cb6859.png)
Without flags:
![toc2](https://user-images.githubusercontent.com/11630230/64030195-c2f16b80-cb4e-11e9-940c-c31e24c725f2.png)
Less space:
![toc3](https://user-images.githubusercontent.com/11630230/64030198-c553c580-cb4e-11e9-89e4-e07b60bf1d93.png)

[toc3.psd.zip](https://github.com/NMRLipids/NMRlipidsIVotherHGs/files/3560384/toc3.psd.zip)

**Comment by markussmiettinen** [comment]
Following skype chats with @mattijavanainen and @ohsOllila on Friday, here is an updated version:
![toc_1sep1](https://user-images.githubusercontent.com/5721866/64075893-42517d00-ccbe-11e9-94f9-032ba73becd5.jpg)
I like @jsmaatta's proposal of including NMR spectra. I would either add just the splittings on beta and alpha (as these are used for the assessment of FFs on the right):
![toc_1sep2](https://user-images.githubusercontent.com/5721866/64075919-cd327780-ccbe-11e9-97b0-03f2784e103b.jpg)
or then both the splittings and the dimension showing the 13C chemical shifts:
![toc_1sep3](https://user-images.githubusercontent.com/5721866/64075931-f8b56200-ccbe-11e9-83c8-f53a7ae7b685.jpg)
However, I do not have Photoshop, and thus could not easily make the backgrounds transparent here... Could you do this, @jsmaatta? The figure I used is PShgSIGNS.pdf, so if you would just make a pdf version of that with transparent background (plus maybe also use to the nice cyan colour you used above)?

**Comment by jsmaatta** [comment]
Sure,

Here are cyan and black versions of both 'splittings only' and 'splittings+13C shift' images. Also a psd just in case. Since less is more I prefer the version with splittings only. The 13C-shift is more widely understandable though as it is taught in every basic biochemistry class.

-Jukka 

![toc_cyan](https://user-images.githubusercontent.com/11630230/64078117-8608ae80-ccdf-11e9-8e57-ea45198c13ed.png)
![toc_black](https://user-images.githubusercontent.com/11630230/64078120-8a34cc00-ccdf-11e9-9b44-05ae3eac70c3.png)
![toc_cyan_13C](https://user-images.githubusercontent.com/11630230/64078122-8c972600-ccdf-11e9-9ffc-f94eca1025f1.png)
![toc_black_13C](https://user-images.githubusercontent.com/11630230/64078123-8dc85300-ccdf-11e9-8dcd-e58fd881cfda.png)
[toc_layers.psd.zip](https://github.com/NMRLipids/NMRlipidsIVotherHGs/files/3563594/toc_layers.psd.zip)

**Comment by mattijavanainen** [comment]
I'd like to remind you that the TOC is 8.25 cm wide so these spectra won't be visible in the figure. How about we only show the 13C shift spectrum with alpha / beta labels next to be peaks and the xlabel next to the axis on the right. This way we could increase the size of the spectrum to span the whole bilayer width and it would likely be large enough to be readable. 

The other thing that bothers me is that CHARMM36 seems to be in the green 'more realistic' region, although the abstract strongly suggests otherwise. How about connecting the circles with lines to the scale so that even CHARMM36 is pointed to the red region? I am afraid this could make things less clear though.

Other than these two things, I really like the current draft of the TOC!

**Comment by markussmiettinen** [comment]
Thanks @jsmaatta, looks nice! Could you also share those transparent plot elements as separate files? I can't open them from the psd, and would like to address the points by @mattijavanainen.

**Comment by jsmaatta** [comment]
Good points! Decided to do a transparent png from PShgSIGNS.pdf so its a bit higher resolution.

![transparentcyan](https://user-images.githubusercontent.com/11630230/64081026-fe816680-cd03-11e9-99a7-450e52ff8df4.png)
![transparent](https://user-images.githubusercontent.com/11630230/64081027-ffb29380-cd03-11e9-8a75-9b71f4c6408a.png)

**Comment by ohsOllila** [comment]
As you can see, the intensity of the peaks in the dipolar slice of the alpha carbon are not as large as often observed in these experiments. I think that the order parameter value is still reliable, especially because it is the same as from 2H NMR experiments, but maybe we should not shown the worst example of the dipolar slice in the TOC. 

Regarding the CHARMM36 in the green, abstract says "We show large discrepancies between different force-fields and that none of the models reproduces the NMR data within experimental accuracy. However, the best MD models can detect the most essential differences between PC and PS headgroup structures." Also, the axis actually ends to "more realistic". Therefore, I do not think that CHARMM is too green now.

**Comment by markussmiettinen** [comment]
How about this?

![toc_withNMR](https://user-images.githubusercontent.com/5721866/64082528-c5032800-cd10-11e9-9c5b-47475407a9a4.jpg)

**Comment by markussmiettinen** [comment]
Committed the above now in #123 in pdf, png, tiff, and jpg, I guess we can close this.

**Comment by markussmiettinen** [comment]
Ivan Gushchin  commented per email: _it is not immediately obvious that the force fields are ranked according to α and β matching (are they?) and not overall (according to Σ), maybe this can be somehow amended? Maybe by changing "more realistic" to "more realistic S_CH^α and  S_CH^β" ? Also not particularly important, several minor issues (highlighted in magenta in the attachment): 1) right side of the image seems to have transparent background, because of which it becomes beige in PDF; 2) remains of some spurious trace; 3) some weird split in the plot; 4) weird displacement of the tick's upper part._
![ToC](https://user-images.githubusercontent.com/5721866/66923501-35e47200-f029-11e9-900a-c846006f256d.jpg)

**Comment by markussmiettinen** [comment]
I am a bit baffled as to where ACS has taken this figure. None of the tiff, jpg, png, or pdf files we have on the github repository has the bugs 3) and 4) mentioned by Ivan above. Also this ACS figure seems to be made up of a collection of panels, which one sees by zooming in; that these panels don't match up is the reason for the bugs 3) and 4), actually.

Has anyone experienced this before with ACS?

**Comment by ivan-gushchin-mipt** [comment]
Indeed the bugs 3) and 4) are because of the panels - I thought that this was deliberate. Also the lipid molecule that is highlighted is darker on the right side (to the right of the vertical line going upwards from 3) - I thought that maybe this was done to highlight the head group, but apparently it was not so in the submitted version.

**Comment by markussmiettinen** [comment]
Maybe the reason for the problems is that we actually included the pdf version of the TOC figure in the submitted revised pdf:

`Manuscript bb$ grep TOC manuscriptPS.tex`
`  \includegraphics[width=8.5cm]{../Figs/TOC_graphic.pdf}`
`Manuscript bb$`

and the ACS robot then somehow mangled that into its present glory. (I think they ask for a tiff version of the TOC figure... but then again LaTeX does not like tiff, so one typically gives a png instead.)

Anyhow, I think it should be fine if we just **send them the tiff that is now in the Figs folder**. It also has no alpha channel, so the background should be all white. I think this would settle all the four minor issues raised by @ivan-gushchin-mipt.

Concerning @ivan-gushchin-mipt's major point. The TOC figure will always be accompanied by the paper title "Headgroup Structure and Cation Binding in Phosphatidylserine Lipid Bilayers". I hope this will be enough to suggest that the ranking is based on just alpha and beta.

**Comment by ohsOllila** [comment]
I have now uploaded figure in tiff format.
