### ISSUE TITLE
Fig S7 bottom right showing non-converged data for Charmm36

### ISSUE THREAD

**Issue by jmelcr** [NMRLipids/NMRlipidsIVotherHGs#94]
In Fig S7 bottom right, which shows dihedral angle distribution for Ca-Cb-Cg-Og contains non-converged data for Charmm36. COO- group has two oxygen atoms pointing at distinct directions, which has to lead to two distinct maxima in the distribution. In the simulation time scales, the rotation of the COO- group in Charmm36 model apparently does not occur and, hence, only one half of the distribution is observed. Averaging over the two in simulation chemically identical oxygen atoms shall be done to correct for this artifact and radiate a non-confusing message.

**Comment by ohsOllila** [comment]
Indeed, the rotation of the COO- group does not occur in CHARMM36 and Slipids models, which have the best headgroup order parameters among the tested models. Therefore we suggest in the manuscript that this is probably a more realistic scenario than the rotation observed in other simulation models.  

I do not fully understand some parts of your comment, maybe you could little bit specify these:

> In Fig S7 bottom right, which shows dihedral angle distribution for Ca-Cb-Cg-Og contains non-converged data for Charmm36.

In what sense the data is not converged? Do you think that the COO- rotations are not converged in CHARMM36, i.e., if we would run long enough we would see rotation? If yes, is there some reason why this would be expected?

> COO- group has two oxygen atoms pointing at distinct directions, which has to lead to two distinct maxima in the distribution.

I do not understand why this has to be the case? If COO- does not rotate, then there is only one maxima, which is the case in CHARMM36 and Slipids

> Averaging over the two in simulation chemically identical oxygen atoms shall be done to correct for this artifact and radiate a non-confusing message.

I am not sure if I understand this. If we would do this for CHARMM36 and Slipids, it would look like that COO- would rotate, which is not actually the case in these simulations.

**Comment by jmelcr** [comment]
> In what sense the data is not converged? Do you think that the COO- rotations are not converged in CHARMM36, i.e., if we would run long enough we would see rotation? 

Yes, the two Oxygen atoms are equivalent and the COO- group can in principle rotate in the CHARMM36 model, so after running a long enough simulation the rotation of the group shall appear. However, no such rotation is observed judging from the plot in the Figure S7.


> I do not understand why this has to be the case? If COO- does not rotate, then there is only one maxima, which is the case in CHARMM36 and Slipids

If there is no rotation of the COO- group, then there is indeed only one distribution peak for each oxygen atom in the group (O13A and O13B). This is clearly seen from the construction of the internal dihedral coordinates - O13A (i.e., the plotted one, I suppose) points to more "cis" direction meaning that opposing O13B has to necessarily point to the other "trans"-like direction. Hence, there are two separate distribution densities for each oxygen atom when the group is not rotating.


> I am not sure if I understand this. If we would do this for CHARMM36 and Slipids, it would look like that COO- would rotate, which is not actually the case in these simulations.

Because there is no distinction in the chemical figure or in text between O13A resp. O13B, the impression made by the figure is that the distribution represents both of the oxygen atoms. This is not the case for CHARMM36, where the distribution only for one Oxygen atom is plotted making an impression that both of the oxygens adopt somewhat the same orientation within the molecule - which is dramatically different from the other models. 

The truth is that the average orientation is rather shifted to different values (for both oxygens) compared to other models. The fact that the COO- group in the CHARMM36 model does not practically rotate in the time scales of our simulations does not lead to any superiority of the model, which is currently the impression I get from the manuscript. Simply swapping the two oxygen atoms one for another (i.e., O13A and O13B) will not lead to different interactions, all structural parameters will remain the same, while the distribution of the discussed dihedral angle will change dramatically in the figure S7.

For this reason, I think that the argument about the importance of structural rigidity of COO- group judging from the CHARMM36 model shall be refined.

**Comment by ohsOllila** [comment]
> Yes, the two Oxygen atoms are equivalent and the COO- group can in principle rotate in the CHARMM36 model, so after running a long enough simulation the rotation of the group shall appear.

Are you sure about this? For me, it seems that dihedral term in line 1198 in this file https://zenodo.org/record/1493246/files/POPS.itp would not allow such rotation.

> Because there is no distinction in the chemical figure or in text between O13A resp. O13B, the impression made by the figure is that the distribution represents both of the oxygen atoms. This is not the case for CHARMM36, where the distribution only for one Oxygen atom is plotted making an impression that both of the oxygens adopt somewhat the same orientation within the molecule - which is dramatically different from the other models.

I do not get this impression from the figure. On the top of figure S7 there is the chemical structure, where another one of the oxygens is labeled as O_\gamma, and then this is used in dihedral plot labels. I think that it is clear that in all the models only other oxygen is used to generate the dihedral distributions and the structure figures (@pbuslaev please correct if I am wrong) and that the difference in these arises because in CHARMM and Slipids the oxygens do not rotate, while in other models they do.

> The fact that the COO- group in the CHARMM36 model does not practically rotate in the time scales of our simulations does not lead to any superiority of the model, which is currently the impression I get from the manuscript.

The manuscript is currently saying that based on order parameters, CHARMM and Slipids best describe the PS headgroup and differences to PC, and one of the main differences in these models to the others is the lack of rotation of the oxygens. Therefore, it is stated that the best MD models suggest that the carboxyl group in the PS headgroup does not rotate freely. The manuscript also says that none of the models is actually correct, and therefore we need better models.  

> Simply swapping the two oxygen atoms one for another (i.e., O13A and O13B) will not lead to different interactions, all structural parameters will remain the same, while the distribution of the discussed dihedral angle will change dramatically in the figure S7.

This may be true, but my feeling is that entropy related to the rotation could be potentially relevant for, e.g., protein-PS headgroup interactions. This is currently quite different in different models and our statement is that the models that do not rotate give better order parameters.

**Comment by ohsOllila** [comment]
What could happen, is that in models with binodal distribution, (i.e., all the other than CHARMM and Slipids), the oxygens would be rigid as well, but the dihedral distributions show presence for both orientations due to the initial structure. However, this seems unlikely for most of the models because there seem to be finite probabilities for intermediate states and symmetric distributions, indicating the transitions actually happen. The exceptions would be Berger and Gromos-CKPM where probabilities of the transition states seem to be zero. This could be checked by plotting the distributions from individual molecules. Even if this were the case, the statement that best models suggest that the oxygens are rigid is still valid. 

In the text, the rigidity of oxygens is only one of the structural details which is discussed. However, it is mentioned in the abstract. We could change the abstract to be less concrete by saying something more general about structural ensembles, but then it would be less concrete.

**Comment by jmelcr** [comment]
> Are you sure about this? For me, it seems that dihedral term in line 1198 in this file https://zenodo.org/record/1493246/files/POPS.itp would not allow such rotation.

The mentioned improper dihedral maintains the Cb-CgOO group planar, but does not restrict motion with respect to Calpha or the nitrogen. 

> In the text, the rigidity of oxygens is only one of the structural details which is discussed. However, it is mentioned in the abstract. We could change the abstract to be less concrete by saying something more general about structural ensembles, but then it would be less concrete.

I would strongly suggest it!
Consider [ECC-POPS model](https://github.com/jmelcr/ecc_lipids), which can rotate freely and also gives very good structural predictions, especially response to the ions.

**Comment by ohsOllila** [comment]
> > Are you sure about this? For me, it seems that dihedral term in line 1198 in this file https://zenodo.org/record/1493246/files/POPS.itp would not allow such rotation.
> 
> The mentioned improper dihedral maintains the Cb-CgOO group planar, but does not restrict motion with respect to Calpha or the nitrogen.
> 
> > In the text, the rigidity of oxygens is only one of the structural details which is discussed. However, it is mentioned in the abstract. We could change the abstract to be less concrete by saying something more general about structural ensembles, but then it would be less concrete.
> 
> I would strongly suggest it!
> Consider [ECC-POPS model](https://github.com/jmelcr/ecc_lipids), which can rotate freely and also gives very good structural predictions, especially response to the ions.

Right, I looked it wrong.

> I would strongly suggest it!
> Consider [ECC-POPS model](https://github.com/jmelcr/ecc_lipids), which can rotate freely and also gives very good structural predictions, especially response to the ions.

I have now update the abstract in this commit https://github.com/NMRLipids/NMRlipidsIVotherHGs/commit/6be8147906b6203153cbc8b977a7ede08c024cfd
However, note that ECC-POPS does not replicate the experimentally observed larger-than-in-PC forking of the α-carbon in PS or significantly smaller β-carbon order parameters for PS compared to PC. The reproduction of these features is the main reasons why CHARMM and Slipids are considered to best reproduce the differences between lipids. Therefore, the ECC-POPS results would further support the argument that rigidity of carboxylate would be important for the difference between PC and PS.

**Comment by jmelcr** [comment]
Good, I think it looks better like this. The abstract/text can be probably sharpened in the following direction:
` after considering all of the gathered data from various models, less flexible/more rigid description of the head group gives generally better agreement with experimental data `
without commenting on the rotational freedom of specific groups.

I feel this issue is solved and we can close it.
